class SvgPath{
  static const splashImage = "assets/svg/splashImage.svg";
  static const loginImage = "assets/svg/loginImage.svg";
  static const person = "assets/svg/person.svg";
  static const smallCar = "assets/svg/smallCar.svg";
  static const bigCar = "assets/svg/bigCar.svg";
  static const innerWash = "assets/svg/innerWash.svg";
  static const outerWash = "assets/svg/outerWash.svg";
  static const washingMachine = "assets/svg/washingMachine.svg";
  static const applePay = "assets/svg/applePay.svg";
  static const coupon = "assets/svg/coupon.svg";
  static const creditCard = "assets/svg/creditCard.svg";
  static const money = "assets/svg/money.svg";
  static const wallet = "assets/svg/wallet.svg";
  static const masterCard = "assets/svg/masterCard.svg";
  static const visa = "assets/svg/visa.svg";
  static const addIcon = "assets/svg/addIcon.svg";
  static const call = "assets/svg/call.svg";
  static const message = "assets/svg/message.svg";
  static const edit = "assets/svg/edit.svg";
  static const trash = "assets/svg/trash.svg";
  static const location = "assets/svg/location.svg";
  static const profileMessage = "assets/svg/profileMessage.svg";
  static const infoCircle = "assets/svg/infoCircle.svg";
  static const messageQuestion = "assets/svg/messageQuestion.svg";
  static const driverType = "assets/svg/driverType.svg";
  static const userType = "assets/svg/userType.svg";
  static const menuDrawer = "assets/svg/menuDrawer.svg";
  static const notification = "assets/svg/notification.svg";
  static const home = "assets/svg/home.svg";
  static const messageText = "assets/svg/messageText.svg";
  static const myOrders = "assets/svg/myOrders.svg";
  static const personOutlined = "assets/svg/personOutlined.svg";
  static const star = "assets/svg/star.svg";
  static const send = "assets/svg/send.svg";
  static const locationOnMapSvg = "assets/svg/locationOnMapSvg.svg";
  static const logout = "assets/svg/logout.svg";
  static const arrowDown = "assets/svg/arrowDown.svg";
  SvgPath._();
}

